name: flutter_marquee
description: A Flutter widget that creates a smooth scrolling marquee text effect, automatically handling text that exceeds screen width.
version: 1.0.0
homepage: https://github.com/jonathanMNg/flutter_marquee
repository: https://github.com/jonathanMNg/flutter_marquee
issue_tracker: https://github.com/jonathanMNg/flutter_marquee/issues
documentation: https://github.com/jonathanMNg/flutter_marquee#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  # This section is intentionally left empty as this is a pure Dart package
